version: '2'
services:

  data:
    build: ./data/owncloud

  postgres_data:
    build: ./data/db

  postgres:
    build: ./db
    depends_on:
      - postgres_data
    volumes_from:
      - postgres_data:rw
    expose:
      - 5432
    networks:
      - backend_db

  app:
    build: ./nginx
    depends_on:
      - data
      - postgres
    volumes_from:
      - data:rw
    links:
      - postgres:postgres
    expose:
      - 80
    networks:
      - backend_app
      - backend_db

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    expose:
      - 9200
      - 9300
    networks:
      - backend_app

  waf:
    build: ./waf
    depends_on:
      - app
      - elasticsearch
    links:
      - app:owncloud
      - elasticsearch:elasticsearch
    environment:
      - LEARNING_MODE=yes
      - PROXY_REDIRECT_IP=owncloud
    ports:
      - "443:443"
    networks:
      - frontend
      - backend_app

networks:
  frontend:
    driver: bridge
  backend_db:
    driver: bridge
  backend_app:
    driver: bridge
